"""Shared plumbing for sim 2: paths, model, pricing, API calls with logging, roster, headers."""
import hashlib, json, os, re, threading, time
from pathlib import Path

import anthropic

SIM_ROOT = Path(__file__).resolve().parent.parent
CORPUS = Path(os.environ.get("EFS_CORPUS", Path.home() / "ox" / "epistemic-futures-corpus"))
DOSSIERS = CORPUS / "dossiers"
INDEX_DIR = SIM_ROOT / "index"          # gitignored; rebuild with build_index.py
CARDS_DIR = SIM_ROOT / "cards"
SUMMIT = CORPUS / "summit" / "website"

MODEL = "claude-opus-5-5"
# USD per million tokens. Opus 5.5 list price as recorded in the job notes on 2026-09-23;
# cache write assumed 1.25x input, cache read as recorded ($0.20). RUN.md records raw token
# counts so cost can be recomputed if these are wrong.
PRICE = {"input": 4.0, "output": 20.0, "cache_write": 5.0, "cache_read": 0.20}

SIM_HEADER = ("> SIMULATED. This document was generated by an AI agent predicting the output of the "
              "Epistemic Futures Summit; no attendee wrote or endorsed any of it.")

_client = None
def client():
    global _client
    if _client is None:
        key = os.environ.get("CLAUDE_API_KEY") or os.environ.get("ANTHROPIC_API_KEY")
        _client = anthropic.Anthropic(api_key=key, max_retries=6, timeout=600)
    return _client


class CallLog:
    """Append-only JSONL log of every API call + running cost. Thread-safe."""
    def __init__(self, path):
        self.path = Path(path); self.path.parent.mkdir(parents=True, exist_ok=True)
        self.lock = threading.Lock()
        self.totals = {"input": 0, "output": 0, "cache_write": 0, "cache_read": 0, "calls": 0, "usd": 0.0}
        if self.path.exists():
            for line in self.path.read_text().splitlines():
                try: self._add(json.loads(line), write=False)
                except Exception: pass

    def _add(self, rec, write=True):
        u = rec["usage"]
        self.totals["input"] += u["input"]; self.totals["output"] += u["output"]
        self.totals["cache_write"] += u["cache_write"]; self.totals["cache_read"] += u["cache_read"]
        self.totals["calls"] += 1; self.totals["usd"] += rec["usd"]
        if write:
            with open(self.path, "a") as f: f.write(json.dumps(rec, ensure_ascii=False) + "\n")

    def add(self, rec):
        with self.lock: self._add(rec)


LOG = None  # set by run.py
def set_log(path):
    global LOG; LOG = CallLog(path); return LOG


def usage_cost(u):
    inp = u.input_tokens or 0; out = u.output_tokens or 0
    cw = getattr(u, "cache_creation_input_tokens", 0) or 0
    cr = getattr(u, "cache_read_input_tokens", 0) or 0
    usd = (inp * PRICE["input"] + out * PRICE["output"] + cw * PRICE["cache_write"] + cr * PRICE["cache_read"]) / 1e6
    return {"input": inp, "output": out, "cache_write": cw, "cache_read": cr}, usd


def prompt_hash(system, messages, tools):
    h = hashlib.sha256()
    h.update(json.dumps({"system": system, "tools": tools}, sort_keys=True, default=str).encode())
    h.update(json.dumps(messages, sort_keys=True, default=str).encode())
    return h.hexdigest()[:16]


def call(*, system, messages, tools=None, max_tokens=8000, effort="medium", tool_choice=None,
         tag="", agent="", phase="", extra=None):
    """One Messages API call with retries, usage logging and cost. Returns the response."""
    kw = dict(model=MODEL, max_tokens=max_tokens, system=system, messages=messages,
              output_config={"effort": effort})
    if tools: kw["tools"] = tools
    if tool_choice: kw["tool_choice"] = tool_choice
    t0 = time.time()
    last = None
    for attempt in range(8):
        try:
            resp = client().messages.create(**kw)
            break
        except (anthropic.RateLimitError, anthropic.APIConnectionError, anthropic.InternalServerError) as e:
            last = e; time.sleep(min(60, 5 * 2 ** attempt))
        except anthropic.APIStatusError as e:
            if e.status_code in (429, 500, 502, 503, 529, 400) and "credit" in str(e).lower():
                last = e; time.sleep(120); continue
            raise
    else:
        raise RuntimeError(f"API call failed after retries: {last}")
    usage, usd = usage_cost(resp.usage)
    rec = {"ts": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()), "agent": agent, "phase": phase, "tag": tag,
           "model": MODEL, "effort": effort, "prompt_hash": prompt_hash(system, messages, tools),
           "stop_reason": resp.stop_reason, "usage": usage, "usd": round(usd, 5), "secs": round(time.time() - t0, 1)}
    if extra: rec.update(extra)
    if LOG: LOG.add(rec)
    return resp


def text_of(resp):
    return "\n".join(b.text for b in resp.content if b.type == "text").strip()


def parse_json(s):
    """Best-effort JSON object extraction from model text."""
    s = s.strip()
    s = re.sub(r"^```(?:json)?\s*|\s*```$", "", s, flags=re.S)
    try: return json.loads(s)
    except Exception: pass
    m = re.search(r"\{.*\}", s, flags=re.S)
    if m:
        try: return json.loads(m.group(0))
        except Exception: pass
    return None


def load_roster():
    """Parse dossiers/00-roster.md → list of {name, slug, affiliation, role}."""
    rows = []
    for line in (DOSSIERS / "00-roster.md").read_text().splitlines():
        if not line.startswith("| ") or line.startswith("| Name") or line.startswith("|---"): continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 4: continue
        m = re.search(r"\[`([a-z0-9-]+)`\]", cells[1])
        if not m: continue
        rows.append({"name": cells[0], "slug": m.group(1), "affiliation": cells[2], "role": cells[3]})
    return rows


def name_of(slug, roster=None):
    roster = roster or load_roster()
    for r in roster:
        if r["slug"] == slug: return r["name"]
    return slug


def words(s): return len(re.findall(r"\S+", s))


def write_md(path, title, body):
    path = Path(path); path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(f"{SIM_HEADER}\n\n# {title}\n\n{body.rstrip()}\n")
